---
name: "🛳  Deploy"
on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: read
  deployments: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  deploy:
    name: 🛳  Deploying
    timeout-minutes: 30
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: "⤵️  Check out code from GitHub"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
        with:
          fetch-depth: 0
      - name: "📦 Setup pnpm"
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - name: "⎔  Setup node"
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - name: "🏗  Prepare"
        run: pnpm install --prod
      - name: "🚀 Publish"
        uses: cloudflare/pages-action@f0a1cd58cd66095dee69bfa18fa5efd1dde93bca # v1.5.0
        with:
          projectName: "osint-framework"
          directory: "public"
          apiToken: ${{ secrets.CF_PAGES_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
